//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 12:32:40 PM CET 
//


package com.osafe.feeds.osafefeeds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BigFishProductFeedType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BigFishProductFeedType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductCategory" type="{}ProductCategoryType"/>
 *         &lt;element name="Products" type="{}ProductsType"/>
 *         &lt;element name="ProductAssociation" type="{}ProductAssociationType"/>
 *         &lt;element name="ProductFeatureSwatch" type="{}ProductFeatureSwatchType"/>
 *         &lt;element name="ProductManufacturer" type="{}ProductManufacturerType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BigFishProductFeedType", propOrder = {
    "productCategory",
    "products",
    "productAssociation",
    "productFeatureSwatch",
    "productManufacturer"
})
public class BigFishProductFeedType {

    @XmlElement(name = "ProductCategory", required = true)
    protected ProductCategoryType productCategory;
    @XmlElement(name = "Products", required = true)
    protected ProductsType products;
    @XmlElement(name = "ProductAssociation", required = true)
    protected ProductAssociationType productAssociation;
    @XmlElement(name = "ProductFeatureSwatch", required = true)
    protected ProductFeatureSwatchType productFeatureSwatch;
    @XmlElement(name = "ProductManufacturer", required = true)
    protected ProductManufacturerType productManufacturer;

    /**
     * Gets the value of the productCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCategoryType }
     *     
     */
    public ProductCategoryType getProductCategory() {
        return productCategory;
    }

    /**
     * Sets the value of the productCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCategoryType }
     *     
     */
    public void setProductCategory(ProductCategoryType value) {
        this.productCategory = value;
    }

    /**
     * Gets the value of the products property.
     * 
     * @return
     *     possible object is
     *     {@link ProductsType }
     *     
     */
    public ProductsType getProducts() {
        return products;
    }

    /**
     * Sets the value of the products property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductsType }
     *     
     */
    public void setProducts(ProductsType value) {
        this.products = value;
    }

    /**
     * Gets the value of the productAssociation property.
     * 
     * @return
     *     possible object is
     *     {@link ProductAssociationType }
     *     
     */
    public ProductAssociationType getProductAssociation() {
        return productAssociation;
    }

    /**
     * Sets the value of the productAssociation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductAssociationType }
     *     
     */
    public void setProductAssociation(ProductAssociationType value) {
        this.productAssociation = value;
    }

    /**
     * Gets the value of the productFeatureSwatch property.
     * 
     * @return
     *     possible object is
     *     {@link ProductFeatureSwatchType }
     *     
     */
    public ProductFeatureSwatchType getProductFeatureSwatch() {
        return productFeatureSwatch;
    }

    /**
     * Sets the value of the productFeatureSwatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductFeatureSwatchType }
     *     
     */
    public void setProductFeatureSwatch(ProductFeatureSwatchType value) {
        this.productFeatureSwatch = value;
    }

    /**
     * Gets the value of the productManufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link ProductManufacturerType }
     *     
     */
    public ProductManufacturerType getProductManufacturer() {
        return productManufacturer;
    }

    /**
     * Sets the value of the productManufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductManufacturerType }
     *     
     */
    public void setProductManufacturer(ProductManufacturerType value) {
        this.productManufacturer = value;
    }

}
