//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 02:09:28 PM CET 
//


package com.osafe.feeds.osafefeeds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderHeaderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderHeaderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderTotalItem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderTotalAdjustment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderShippingChargeGross" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderTotalTax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrderTotalNet" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderHeaderType", propOrder = {
    "orderId",
    "orderDate",
    "orderTotalItem",
    "orderTotalAdjustment",
    "orderShippingChargeGross",
    "orderTotalTax",
    "orderTotalNet",
    "currency"
})
public class OrderHeaderType {

    @XmlElement(name = "OrderId", required = true)
    protected String orderId;
    @XmlElement(name = "OrderDate", required = true)
    protected String orderDate;
    @XmlElement(name = "OrderTotalItem", required = true)
    protected String orderTotalItem;
    @XmlElement(name = "OrderTotalAdjustment", required = true)
    protected String orderTotalAdjustment;
    @XmlElement(name = "OrderShippingChargeGross", required = true)
    protected String orderShippingChargeGross;
    @XmlElement(name = "OrderTotalTax", required = true)
    protected String orderTotalTax;
    @XmlElement(name = "OrderTotalNet", required = true)
    protected String orderTotalNet;
    @XmlElement(name = "Currency", required = true)
    protected String currency;

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the orderDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderDate(String value) {
        this.orderDate = value;
    }

    /**
     * Gets the value of the orderTotalItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderTotalItem() {
        return orderTotalItem;
    }

    /**
     * Sets the value of the orderTotalItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderTotalItem(String value) {
        this.orderTotalItem = value;
    }

    /**
     * Gets the value of the orderTotalAdjustment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderTotalAdjustment() {
        return orderTotalAdjustment;
    }

    /**
     * Sets the value of the orderTotalAdjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderTotalAdjustment(String value) {
        this.orderTotalAdjustment = value;
    }

    /**
     * Gets the value of the orderShippingChargeGross property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderShippingChargeGross() {
        return orderShippingChargeGross;
    }

    /**
     * Sets the value of the orderShippingChargeGross property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderShippingChargeGross(String value) {
        this.orderShippingChargeGross = value;
    }

    /**
     * Gets the value of the orderTotalTax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderTotalTax() {
        return orderTotalTax;
    }

    /**
     * Sets the value of the orderTotalTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderTotalTax(String value) {
        this.orderTotalTax = value;
    }

    /**
     * Gets the value of the orderTotalNet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderTotalNet() {
        return orderTotalNet;
    }

    /**
     * Sets the value of the orderTotalNet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderTotalNet(String value) {
        this.orderTotalNet = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

}
