//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 02:09:28 PM CET 
//


package com.osafe.feeds.osafefeeds;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ProductStore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Customer" type="{}CustomerType"/>
 *         &lt;element name="OrderHeader" type="{}OrderHeaderType"/>
 *         &lt;element name="CartPromotion" type="{}CartPromotionType" maxOccurs="unbounded"/>
 *         &lt;element name="OrderLineItems" type="{}OrderLineItemsType"/>
 *         &lt;element name="OrderPayment" type="{}OrderPaymentType"/>
 *         &lt;element name="OrderAttribute" type="{}OrderAttributeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderType", propOrder = {
    "productStore",
    "customer",
    "orderHeader",
    "cartPromotion",
    "orderLineItems",
    "orderPayment",
    "orderAttribute"
})
public class OrderType {

    @XmlElement(name = "ProductStore", required = true)
    protected String productStore;
    @XmlElement(name = "Customer", required = true)
    protected CustomerType customer;
    @XmlElement(name = "OrderHeader", required = true)
    protected OrderHeaderType orderHeader;
    @XmlElement(name = "CartPromotion", required = true)
    protected List<CartPromotionType> cartPromotion;
    @XmlElement(name = "OrderLineItems", required = true)
    protected OrderLineItemsType orderLineItems;
    @XmlElement(name = "OrderPayment", required = true)
    protected OrderPaymentType orderPayment;
    @XmlElement(name = "OrderAttribute", required = true)
    protected OrderAttributeType orderAttribute;

    /**
     * Gets the value of the productStore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductStore() {
        return productStore;
    }

    /**
     * Sets the value of the productStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductStore(String value) {
        this.productStore = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerType }
     *     
     */
    public CustomerType getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerType }
     *     
     */
    public void setCustomer(CustomerType value) {
        this.customer = value;
    }

    /**
     * Gets the value of the orderHeader property.
     * 
     * @return
     *     possible object is
     *     {@link OrderHeaderType }
     *     
     */
    public OrderHeaderType getOrderHeader() {
        return orderHeader;
    }

    /**
     * Sets the value of the orderHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderHeaderType }
     *     
     */
    public void setOrderHeader(OrderHeaderType value) {
        this.orderHeader = value;
    }

    /**
     * Gets the value of the cartPromotion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cartPromotion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCartPromotion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CartPromotionType }
     * 
     * 
     */
    public List<CartPromotionType> getCartPromotion() {
        if (cartPromotion == null) {
            cartPromotion = new ArrayList<CartPromotionType>();
        }
        return this.cartPromotion;
    }

    /**
     * Gets the value of the orderLineItems property.
     * 
     * @return
     *     possible object is
     *     {@link OrderLineItemsType }
     *     
     */
    public OrderLineItemsType getOrderLineItems() {
        return orderLineItems;
    }

    /**
     * Sets the value of the orderLineItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderLineItemsType }
     *     
     */
    public void setOrderLineItems(OrderLineItemsType value) {
        this.orderLineItems = value;
    }

    /**
     * Gets the value of the orderPayment property.
     * 
     * @return
     *     possible object is
     *     {@link OrderPaymentType }
     *     
     */
    public OrderPaymentType getOrderPayment() {
        return orderPayment;
    }

    /**
     * Sets the value of the orderPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderPaymentType }
     *     
     */
    public void setOrderPayment(OrderPaymentType value) {
        this.orderPayment = value;
    }

    /**
     * Gets the value of the orderAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link OrderAttributeType }
     *     
     */
    public OrderAttributeType getOrderAttribute() {
        return orderAttribute;
    }

    /**
     * Sets the value of the orderAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderAttributeType }
     *     
     */
    public void setOrderAttribute(OrderAttributeType value) {
        this.orderAttribute = value;
    }

}
