//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 12:32:40 PM CET 
//


package com.osafe.feeds.osafefeeds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PdpAdditionalImageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PdpAdditionalImageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PdpAdditionalThumbImage" type="{}PdpAdditionalThumbImageType"/>
 *         &lt;element name="PdpAdditionalLargeImage" type="{}PdpAdditionalLargeImageType"/>
 *         &lt;element name="PdpAdditionalDetailImage" type="{}PdpAdditionalDetailImageType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PdpAdditionalImageType", propOrder = {
    "pdpAdditionalThumbImage",
    "pdpAdditionalLargeImage",
    "pdpAdditionalDetailImage"
})
public class PdpAdditionalImageType {

    @XmlElement(name = "PdpAdditionalThumbImage", required = true)
    protected PdpAdditionalThumbImageType pdpAdditionalThumbImage;
    @XmlElement(name = "PdpAdditionalLargeImage", required = true)
    protected PdpAdditionalLargeImageType pdpAdditionalLargeImage;
    @XmlElement(name = "PdpAdditionalDetailImage", required = true)
    protected PdpAdditionalDetailImageType pdpAdditionalDetailImage;

    /**
     * Gets the value of the pdpAdditionalThumbImage property.
     * 
     * @return
     *     possible object is
     *     {@link PdpAdditionalThumbImageType }
     *     
     */
    public PdpAdditionalThumbImageType getPdpAdditionalThumbImage() {
        return pdpAdditionalThumbImage;
    }

    /**
     * Sets the value of the pdpAdditionalThumbImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link PdpAdditionalThumbImageType }
     *     
     */
    public void setPdpAdditionalThumbImage(PdpAdditionalThumbImageType value) {
        this.pdpAdditionalThumbImage = value;
    }

    /**
     * Gets the value of the pdpAdditionalLargeImage property.
     * 
     * @return
     *     possible object is
     *     {@link PdpAdditionalLargeImageType }
     *     
     */
    public PdpAdditionalLargeImageType getPdpAdditionalLargeImage() {
        return pdpAdditionalLargeImage;
    }

    /**
     * Sets the value of the pdpAdditionalLargeImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link PdpAdditionalLargeImageType }
     *     
     */
    public void setPdpAdditionalLargeImage(PdpAdditionalLargeImageType value) {
        this.pdpAdditionalLargeImage = value;
    }

    /**
     * Gets the value of the pdpAdditionalDetailImage property.
     * 
     * @return
     *     possible object is
     *     {@link PdpAdditionalDetailImageType }
     *     
     */
    public PdpAdditionalDetailImageType getPdpAdditionalDetailImage() {
        return pdpAdditionalDetailImage;
    }

    /**
     * Sets the value of the pdpAdditionalDetailImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link PdpAdditionalDetailImageType }
     *     
     */
    public void setPdpAdditionalDetailImage(PdpAdditionalDetailImageType value) {
        this.pdpAdditionalDetailImage = value;
    }

}
