//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 12:32:40 PM CET 
//


package com.osafe.feeds.osafefeeds;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProductType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MasterProductId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductStoreId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="InternalName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SalesPitch" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LongDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SpecialInstructions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeliveryInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Directions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TermsAndConds" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Ingredients" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Warnings" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PlpLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PdpLabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductHeight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductWidth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductDepth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Returnable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Taxable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ChargeShipping" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ManufacturerId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FromDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ThruDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProductPrice" type="{}ProductPriceType"/>
 *         &lt;element name="ProductCategoryMember" type="{}ProductCategoryMemberType"/>
 *         &lt;element name="ProductSelectableFeature" type="{}ProductSelectableFeatureType"/>
 *         &lt;element name="ProductDescriptiveFeature" type="{}ProductDescriptiveFeatureType"/>
 *         &lt;element name="ProductImage" type="{}ProductImageType"/>
 *         &lt;element name="GoodIdentification" type="{}GoodIdentificationType"/>
 *         &lt;element name="ProductInventory" type="{}ProductInventoryType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductType", propOrder = {
    "masterProductId",
    "productId",
    "productStoreId",
    "internalName",
    "productName",
    "salesPitch",
    "longDescription",
    "specialInstructions",
    "deliveryInfo",
    "directions",
    "termsAndConds",
    "ingredients",
    "warnings",
    "plpLabel",
    "pdpLabel",
    "productHeight",
    "productWidth",
    "productDepth",
    "returnable",
    "taxable",
    "chargeShipping",
    "manufacturerId",
    "fromDate",
    "thruDate",
    "productPrice",
    "productCategoryMember",
    "productSelectableFeature",
    "productDescriptiveFeature",
    "productImage",
    "goodIdentification",
    "productInventory"
})
public class ProductType {

    @XmlElement(name = "MasterProductId", required = true, defaultValue = "")
    protected String masterProductId;
    @XmlElement(name = "ProductId", required = true, defaultValue = "")
    protected String productId;
    @XmlElement(name = "ProductStoreId", required = true, defaultValue = "")
    protected String productStoreId;
    @XmlElement(name = "InternalName", required = true, defaultValue = "")
    protected String internalName;
    @XmlElement(name = "ProductName", required = true, defaultValue = "")
    protected String productName;
    @XmlElement(name = "SalesPitch", required = true, defaultValue = "")
    protected String salesPitch;
    @XmlElement(name = "LongDescription", required = true, defaultValue = "")
    protected String longDescription;
    @XmlElement(name = "SpecialInstructions", required = true, defaultValue = "")
    protected String specialInstructions;
    @XmlElement(name = "DeliveryInfo", required = true, defaultValue = "")
    protected String deliveryInfo;
    @XmlElement(name = "Directions", required = true, defaultValue = "")
    protected String directions;
    @XmlElement(name = "TermsAndConds", required = true, defaultValue = "")
    protected String termsAndConds;
    @XmlElement(name = "Ingredients", required = true, defaultValue = "")
    protected String ingredients;
    @XmlElement(name = "Warnings", required = true, defaultValue = "")
    protected String warnings;
    @XmlElement(name = "PlpLabel", required = true, defaultValue = "")
    protected String plpLabel;
    @XmlElement(name = "PdpLabel", required = true, defaultValue = "")
    protected String pdpLabel;
    @XmlElement(name = "ProductHeight", required = true, defaultValue = "")
    protected String productHeight;
    @XmlElement(name = "ProductWidth", required = true, defaultValue = "")
    protected String productWidth;
    @XmlElement(name = "ProductDepth", required = true, defaultValue = "")
    protected String productDepth;
    @XmlElement(name = "Returnable", required = true, defaultValue = "")
    protected String returnable;
    @XmlElement(name = "Taxable", required = true, defaultValue = "")
    protected String taxable;
    @XmlElement(name = "ChargeShipping", required = true, defaultValue = "")
    protected String chargeShipping;
    @XmlElement(name = "ManufacturerId", required = true, defaultValue = "")
    protected String manufacturerId;
    @XmlElement(name = "FromDate", required = true, defaultValue = "")
    protected String fromDate;
    @XmlElement(name = "ThruDate", required = true, defaultValue = "")
    protected String thruDate;
    @XmlElement(name = "ProductPrice", required = true)
    protected ProductPriceType productPrice;
    @XmlElement(name = "ProductCategoryMember", required = true)
    protected ProductCategoryMemberType productCategoryMember;
    @XmlElement(name = "ProductSelectableFeature", required = true)
    protected ProductSelectableFeatureType productSelectableFeature;
    @XmlElement(name = "ProductDescriptiveFeature", required = true)
    protected ProductDescriptiveFeatureType productDescriptiveFeature;
    @XmlElement(name = "ProductImage", required = true)
    protected ProductImageType productImage;
    @XmlElement(name = "GoodIdentification", required = true)
    protected GoodIdentificationType goodIdentification;
    @XmlElement(name = "ProductInventory", required = true)
    protected ProductInventoryType productInventory;

    /**
     * Gets the value of the masterProductId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMasterProductId() {
        return masterProductId;
    }

    /**
     * Sets the value of the masterProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMasterProductId(String value) {
        this.masterProductId = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the productStoreId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductStoreId() {
        return productStoreId;
    }

    /**
     * Sets the value of the productStoreId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductStoreId(String value) {
        this.productStoreId = value;
    }

    /**
     * Gets the value of the internalName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalName() {
        return internalName;
    }

    /**
     * Sets the value of the internalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalName(String value) {
        this.internalName = value;
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the salesPitch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesPitch() {
        return salesPitch;
    }

    /**
     * Sets the value of the salesPitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesPitch(String value) {
        this.salesPitch = value;
    }

    /**
     * Gets the value of the longDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongDescription() {
        return longDescription;
    }

    /**
     * Sets the value of the longDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongDescription(String value) {
        this.longDescription = value;
    }

    /**
     * Gets the value of the specialInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialInstructions() {
        return specialInstructions;
    }

    /**
     * Sets the value of the specialInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialInstructions(String value) {
        this.specialInstructions = value;
    }

    /**
     * Gets the value of the deliveryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryInfo() {
        return deliveryInfo;
    }

    /**
     * Sets the value of the deliveryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryInfo(String value) {
        this.deliveryInfo = value;
    }

    /**
     * Gets the value of the directions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirections() {
        return directions;
    }

    /**
     * Sets the value of the directions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirections(String value) {
        this.directions = value;
    }

    /**
     * Gets the value of the termsAndConds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermsAndConds() {
        return termsAndConds;
    }

    /**
     * Sets the value of the termsAndConds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermsAndConds(String value) {
        this.termsAndConds = value;
    }

    /**
     * Gets the value of the ingredients property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIngredients() {
        return ingredients;
    }

    /**
     * Sets the value of the ingredients property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIngredients(String value) {
        this.ingredients = value;
    }

    /**
     * Gets the value of the warnings property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarnings() {
        return warnings;
    }

    /**
     * Sets the value of the warnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarnings(String value) {
        this.warnings = value;
    }

    /**
     * Gets the value of the plpLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlpLabel() {
        return plpLabel;
    }

    /**
     * Sets the value of the plpLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlpLabel(String value) {
        this.plpLabel = value;
    }

    /**
     * Gets the value of the pdpLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdpLabel() {
        return pdpLabel;
    }

    /**
     * Sets the value of the pdpLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdpLabel(String value) {
        this.pdpLabel = value;
    }

    /**
     * Gets the value of the productHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductHeight() {
        return productHeight;
    }

    /**
     * Sets the value of the productHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductHeight(String value) {
        this.productHeight = value;
    }

    /**
     * Gets the value of the productWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductWidth() {
        return productWidth;
    }

    /**
     * Sets the value of the productWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductWidth(String value) {
        this.productWidth = value;
    }

    /**
     * Gets the value of the productDepth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductDepth() {
        return productDepth;
    }

    /**
     * Sets the value of the productDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductDepth(String value) {
        this.productDepth = value;
    }

    /**
     * Gets the value of the returnable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnable() {
        return returnable;
    }

    /**
     * Sets the value of the returnable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnable(String value) {
        this.returnable = value;
    }

    /**
     * Gets the value of the taxable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxable() {
        return taxable;
    }

    /**
     * Sets the value of the taxable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxable(String value) {
        this.taxable = value;
    }

    /**
     * Gets the value of the chargeShipping property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChargeShipping() {
        return chargeShipping;
    }

    /**
     * Sets the value of the chargeShipping property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChargeShipping(String value) {
        this.chargeShipping = value;
    }

    /**
     * Gets the value of the manufacturerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturerId() {
        return manufacturerId;
    }

    /**
     * Sets the value of the manufacturerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturerId(String value) {
        this.manufacturerId = value;
    }

    /**
     * Gets the value of the fromDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromDate(String value) {
        this.fromDate = value;
    }

    /**
     * Gets the value of the thruDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThruDate() {
        return thruDate;
    }

    /**
     * Sets the value of the thruDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThruDate(String value) {
        this.thruDate = value;
    }

    /**
     * Gets the value of the productPrice property.
     * 
     * @return
     *     possible object is
     *     {@link ProductPriceType }
     *     
     */
    public ProductPriceType getProductPrice() {
        return productPrice;
    }

    /**
     * Sets the value of the productPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductPriceType }
     *     
     */
    public void setProductPrice(ProductPriceType value) {
        this.productPrice = value;
    }

    /**
     * Gets the value of the productCategoryMember property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCategoryMemberType }
     *     
     */
    public ProductCategoryMemberType getProductCategoryMember() {
        return productCategoryMember;
    }

    /**
     * Sets the value of the productCategoryMember property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCategoryMemberType }
     *     
     */
    public void setProductCategoryMember(ProductCategoryMemberType value) {
        this.productCategoryMember = value;
    }

    /**
     * Gets the value of the productSelectableFeature property.
     * 
     * @return
     *     possible object is
     *     {@link ProductSelectableFeatureType }
     *     
     */
    public ProductSelectableFeatureType getProductSelectableFeature() {
        return productSelectableFeature;
    }

    /**
     * Sets the value of the productSelectableFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductSelectableFeatureType }
     *     
     */
    public void setProductSelectableFeature(ProductSelectableFeatureType value) {
        this.productSelectableFeature = value;
    }

    /**
     * Gets the value of the productDescriptiveFeature property.
     * 
     * @return
     *     possible object is
     *     {@link ProductDescriptiveFeatureType }
     *     
     */
    public ProductDescriptiveFeatureType getProductDescriptiveFeature() {
        return productDescriptiveFeature;
    }

    /**
     * Sets the value of the productDescriptiveFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductDescriptiveFeatureType }
     *     
     */
    public void setProductDescriptiveFeature(ProductDescriptiveFeatureType value) {
        this.productDescriptiveFeature = value;
    }

    /**
     * Gets the value of the productImage property.
     * 
     * @return
     *     possible object is
     *     {@link ProductImageType }
     *     
     */
    public ProductImageType getProductImage() {
        return productImage;
    }

    /**
     * Sets the value of the productImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductImageType }
     *     
     */
    public void setProductImage(ProductImageType value) {
        this.productImage = value;
    }

    /**
     * Gets the value of the goodIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link GoodIdentificationType }
     *     
     */
    public GoodIdentificationType getGoodIdentification() {
        return goodIdentification;
    }

    /**
     * Sets the value of the goodIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoodIdentificationType }
     *     
     */
    public void setGoodIdentification(GoodIdentificationType value) {
        this.goodIdentification = value;
    }

    /**
     * Gets the value of the productInventory property.
     * 
     * @return
     *     possible object is
     *     {@link ProductInventoryType }
     *     
     */
    public ProductInventoryType getProductInventory() {
        return productInventory;
    }

    /**
     * Sets the value of the productInventory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductInventoryType }
     *     
     */
    public void setProductInventory(ProductInventoryType value) {
        this.productInventory = value;
    }

}
